time_precision: MSECS
logging_level: WARNING
reactors:
  frost_bus:
    logging_level: WARNING
    parameters:
      data_model_path: "resources/data_model/frost_bus.yml"
    reactors:
      message_filter:
        logging_level: WARNING
  student:
    logging_level: WARNING
    parameters:
      data_model_path: "resources/data_model/student.yml"
    reactors:
      message_filter:
        logging_level: WARNING
  professor:
    logging_level: WARNING
  publisher:
    logging_level: WARNING
    parameters:
      data_model_path: "resources/data_model/publisher.yml"
    reactors:
      message_filter:
        logging_level: WARNING
  subscriber:
    logging_level: WARNING
    parameters:
      data_model_path: "resources/data_model/subscriber.yml"
    reactors:
      message_filter:
        logging_level: WARNING
