time_precision: MSECS
logging_level: INFO
reactors:
  frost_bus:
    logging_level: INFO
    parameters:
      data_model_path: "resources/data_model/frost_bus.yml"
    reactors:
      message_filter:
        logging_level: INFO
  target:
    logging_level: INFO
    parameters:
      data_model_path: "resources/data_model/target.yml"
    reactors:
      message_filter:
        logging_level: INFO
  initiator:
    logging_level: INFO
  publisher:
    logging_level: INFO
    parameters:
      data_model_path: "resources/data_model/publisher.yml"
    reactors:
      message_filter:
        logging_level: INFO
  subscriber:
    logging_level: INFO
    parameters:
      data_model_path: "resources/data_model/subscriber.yml"
    reactors:
      message_filter:
        logging_level: INFO
  sensor:
    logging_level: INFO
    parameters:
      data_model_path: "resources/data_model/sensor.yml"
  alarm:
    logging_level: INFO
    parameters:
      data_model_path: "resources/data_model/alarm.yml"
  stock_market:
    logging_level: INFO
    parameters:
      data_model_path: "resources/data_model/stock_market.yml"
    reactors:
      message_filter:
        logging_level: INFO
  investor:
    logging_level: INFO
  scheduler:
    logging_level: INFO
    parameters:
      data_model_path: "resources/data_model/scheduler.yml"
      scheduling_instance: "resources/scheduling_instances/test_scheduler.json"
    reactors:
      message_filter:
        logging_level: WARNING
  machine_1:
    logging_level: INFO
    parameters:
      data_model_path: "resources/data_model/machine_1.yml"
    reactors:
      message_filter:
        logging_level: WARNING
  machine_2:
    logging_level: INFO
    parameters:
      data_model_path: "resources/data_model/machine_2.yml"
    reactors:
      message_filter:
        logging_level: WARNING
  
