time_precision: MSECS
logging_level: WARNING
reactors:
  frost_bus:
    logging_level: WARNING
    parameters:
      data_model_path: "resources/data_model/frost_bus.yml"
    reactors:
      message_filter:
        logging_level: WARNING
  student:
    logging_level: WARNING
    parameters:
      data_model_path: "resources/data_model/student.yml"
    reactors:
      message_filter:
        logging_level: WARNING
  master:
    logging_level: WARNING
